site_name: simpleRM docs
theme: readthedocs

pages:
  - 'index.md'
  - 'requirements.md'
  - 'test_notebook.md'

extra_css:
    - css/extra.css
    - css/font_awesome/css/font-awesome.min.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition:
    